apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoflow-dashboard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/andyviet102/ops-repo.git
    targetRevision: main
    path: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-visualizer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
